/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * AdvogadoGUI.java
 *
 * Created on 16/07/2009, 21:57:48
 */

package gui;

import facade.AdvogadoFacade;

/**
 *
 * @author andrehadm
 */
public class AdvogadoGUI extends javax.swing.JFrame {

    /**Atributos*/
    AdvogadoFacade advogadoFacade;

    /** Creates new form AdvogadoGUI */
    public AdvogadoGUI() {
        advogadoFacade = new AdvogadoFacade();
        initComponents();        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        barraDeFerramentas = new javax.swing.JToolBar();
        jButton_ClienteNovo = new javax.swing.JButton();
        jButton_ClientePesquisa = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        jPanel_AreaDeTrabalho = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        barraDeMenu = new javax.swing.JMenuBar();
        jMenu_Arquivo = new javax.swing.JMenu();
        jMenuItem_Sair = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Advogado");
        setName("janelaPrincipal"); // NOI18N

        barraDeFerramentas.setFloatable(false);
        barraDeFerramentas.setRollover(true);

        jButton_ClienteNovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/clienteNovo.png"))); // NOI18N
        jButton_ClienteNovo.setToolTipText("Criar novo cliente");
        jButton_ClienteNovo.setFocusable(false);
        jButton_ClienteNovo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton_ClienteNovo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton_ClienteNovo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_ClienteNovoMouseClicked(evt);
            }
        });
        barraDeFerramentas.add(jButton_ClienteNovo);

        jButton_ClientePesquisa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/clientePesquisa.png"))); // NOI18N
        jButton_ClientePesquisa.setToolTipText("Pesquisar por cliente");
        jButton_ClientePesquisa.setFocusable(false);
        jButton_ClientePesquisa.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton_ClientePesquisa.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        barraDeFerramentas.add(jButton_ClientePesquisa);
        barraDeFerramentas.add(jSeparator1);

        jLabel1.setText("Area de Trabalho");

        javax.swing.GroupLayout jPanel_AreaDeTrabalhoLayout = new javax.swing.GroupLayout(jPanel_AreaDeTrabalho);
        jPanel_AreaDeTrabalho.setLayout(jPanel_AreaDeTrabalhoLayout);
        jPanel_AreaDeTrabalhoLayout.setHorizontalGroup(
            jPanel_AreaDeTrabalhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_AreaDeTrabalhoLayout.createSequentialGroup()
                .addGap(140, 140, 140)
                .addComponent(jLabel1)
                .addContainerGap(551, Short.MAX_VALUE))
        );
        jPanel_AreaDeTrabalhoLayout.setVerticalGroup(
            jPanel_AreaDeTrabalhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_AreaDeTrabalhoLayout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addComponent(jLabel1)
                .addContainerGap(425, Short.MAX_VALUE))
        );

        jMenu_Arquivo.setLabel("Arquivo");

        jMenuItem_Sair.setLabel("Sair");
        jMenuItem_Sair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuItem_SairMouseClicked(evt);
            }
        });
        jMenu_Arquivo.add(jMenuItem_Sair);

        barraDeMenu.add(jMenu_Arquivo);

        jMenu2.setText("Edit");
        barraDeMenu.add(jMenu2);

        setJMenuBar(barraDeMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(barraDeFerramentas, javax.swing.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE)
            .addComponent(jPanel_AreaDeTrabalho, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(barraDeFerramentas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel_AreaDeTrabalho, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem_SairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItem_SairMouseClicked
        System.exit(0);
    }//GEN-LAST:event_jMenuItem_SairMouseClicked

    private void jButton_ClienteNovoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_ClienteNovoMouseClicked
        
        //Com popup
        ClienteGUI clienteGUI = new ClienteGUI(this, rootPaneCheckingEnabled,advogadoFacade);
        clienteGUI.setVisible(true);
        
        //Maneira de Isaac
        /*
        ClienteNovo clienteNovo = new ClienteNovo(advogadoFacade);
        jPanel_AreaDeTrabalho.removeAll();
        jPanel_AreaDeTrabalho.add(clienteNovo);
        jPanel_AreaDeTrabalho.repaint();*/
}//GEN-LAST:event_jButton_ClienteNovoMouseClicked

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {

//ToDo  Ativar quando o programa tiver pronto!!!

//                try {
//                    UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel");
//                } catch (ClassNotFoundException ex) {
//                    Logger.getLogger(AdvogadoGUI.class.getName()).log(Level.SEVERE, null, ex);
//                } catch (InstantiationException ex) {
//                    Logger.getLogger(AdvogadoGUI.class.getName()).log(Level.SEVERE, null, ex);
//                } catch (IllegalAccessException ex) {
//                    Logger.getLogger(AdvogadoGUI.class.getName()).log(Level.SEVERE, null, ex);
//                } catch (UnsupportedLookAndFeelException ex) {
//                    Logger.getLogger(AdvogadoGUI.class.getName()).log(Level.SEVERE, null, ex);
//                }
                new AdvogadoGUI().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToolBar barraDeFerramentas;
    private javax.swing.JMenuBar barraDeMenu;
    private javax.swing.JButton jButton_ClienteNovo;
    private javax.swing.JButton jButton_ClientePesquisa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuItem jMenuItem_Sair;
    private javax.swing.JMenu jMenu_Arquivo;
    private javax.swing.JPanel jPanel_AreaDeTrabalho;
    private javax.swing.JToolBar.Separator jSeparator1;
    // End of variables declaration//GEN-END:variables

}
