/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ClienteRelatorioCidadeGUI.java
 *
 * Created on 06/03/2010, 13:43:51
 */

package gui;

import facade.AdvogadoFacade;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import modelo.Cliente;

/**
 *
 * @author andrehadm
 */
public class ClienteRelatorioCidadeGUI extends javax.swing.JPanel {

    AdvogadoFacade advogadoFacade;

    /** Creates new form ClienteRelatorioCidadeGUI */
    public ClienteRelatorioCidadeGUI(AdvogadoFacade advogadoFacade) {
        this.advogadoFacade = advogadoFacade;
        initComponents();
        carregaClientes();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables

    private void carregaClientes() {
                System.out.println("");
        System.out.println("Carregando clientes");
        List <Cliente> cliente = advogadoFacade.getTodosClientesPorCidade();

        Object[][] clienteTable = new Object[cliente.size()][3]; // Define uma matriz bidimensional para armazenar os valores
        Object[] titulo = new Object[3]; // Define uma matriz unidimensional para armazenar os titulos


        jTable1.removeAll();
        int clienteContador = 0;
        for (Cliente clienteFor : advogadoFacade.getTodosClientesPorCidade()) {
            clienteTable[clienteContador][0] = clienteFor.getId().toString();
            clienteTable[clienteContador][1] = clienteFor.getNome();
            clienteTable[clienteContador][2] = clienteFor.getCidade();
            clienteContador++;
            System.out.println("Cliente: "+ clienteFor.getId() + " - " + clienteFor.getNome());
        }
        //System.out.println("Tamanho da lista de clientes: " + jComboBoxCliente.getItemCount());
        System.out.println("Clientes carregados.");

        // titulos
        titulo[0] = "Id";
        titulo[1] = "Nome";
        titulo[2] = "Cidade"; // criando objeto modelo

        DefaultTableModel modelo = new DefaultTableModel(clienteTable, titulo);

        // definindo o modelo da tabela
        jTable1.setModel(modelo);
    }

}
