/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ProcessoGUI.java
 *
 * Created on 09/08/2009, 21:38:29
 */

package gui;

import excecao.AtributoNaoEncontrado;
import facade.AdvogadoFacade;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JToolBar;
import modelo.Acao;
import modelo.Cliente;
import modelo.Comarca;
import modelo.Fase;
import modelo.Juiz;
import modelo.Vara;

/**
 *
 * @author andrehadm
 */
public class ProcessoGUI extends javax.swing.JPanel {

    private AdvogadoFacade advogadoFacade;
    private JPanel areaDeTrabalho;
    private JToolBar barraDeFerramentas;

    /** Creates new form ClienteGUI */
    public ProcessoGUI(JPanel areaDeTrabalho, JToolBar barra, AdvogadoFacade advogadoFacade) {
        this.advogadoFacade = advogadoFacade;
        this.areaDeTrabalho = areaDeTrabalho;
        this.barraDeFerramentas = barra;
        initComponents();
        carregaComarca();
        carregaVara();
        carregaCliente();
        carregaJuiz();
        carregaFase();
        carregaAcao();
        this.setVisible(true);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelProcesso = new javax.swing.JLabel();
        jTextFieldProcesso = new javax.swing.JTextField();
        jLabelComarca = new javax.swing.JLabel();
        jComboBoxComarca = new javax.swing.JComboBox();
        jLabelVara = new javax.swing.JLabel();
        jComboBoxVara = new javax.swing.JComboBox();
        jLabelTipoDaAcao = new javax.swing.JLabel();
        jComboBoxTipoDaAcao = new javax.swing.JComboBox();
        jButtonNovoTipoDaAcao = new javax.swing.JButton();
        jLabelFase = new javax.swing.JLabel();
        jComboBoxFase = new javax.swing.JComboBox();
        jButtonNovaFase = new javax.swing.JButton();
        jLabelCliente = new javax.swing.JLabel();
        jComboBoxCliente = new javax.swing.JComboBox();
        jLabelStatus = new javax.swing.JLabel();
        jComboBoxStatus1 = new javax.swing.JComboBox();
        jComboBoxStatus2 = new javax.swing.JComboBox();
        jLabelParteOposta = new javax.swing.JLabel();
        jTextFieldParteOposta = new javax.swing.JTextField();
        jLabelAdvogadoOposto = new javax.swing.JLabel();
        jTextFieldAdvogadoOposto = new javax.swing.JTextField();
        jLabelJuiz = new javax.swing.JLabel();
        jComboBoxJuiz = new javax.swing.JComboBox();
        jButtonNovoJuiz = new javax.swing.JButton();
        jLabelValorDaCausa = new javax.swing.JLabel();
        jTextFieldValorDaCausa = new javax.swing.JTextField();
        jLabelHonorarios = new javax.swing.JLabel();
        jTextFieldHonorarios = new javax.swing.JTextField();
        jLabelObservacoes = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaObservacoes = new javax.swing.JTextArea();
        jLabelEstrategia = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextAreaEstrategia = new javax.swing.JTextArea();
        jButtonSalvar = new javax.swing.JButton();
        jButtonLimpar = new javax.swing.JButton();
        jButtonFechar = new javax.swing.JButton();
        jButtonNovaComarca = new javax.swing.JButton();
        jButtonNovaVara = new javax.swing.JButton();

        setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Novo Processo", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP));
        setPreferredSize(new java.awt.Dimension(543, 381));

        jLabelProcesso.setText("Processo");

        jLabelComarca.setText("Comarca");

        jLabelVara.setText("Vara");

        jLabelTipoDaAcao.setText("Tipo da Ação");

        jButtonNovoTipoDaAcao.setText("Novo");
        jButtonNovoTipoDaAcao.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonNovoTipoDaAcaoMouseClicked(evt);
            }
        });

        jLabelFase.setText("Fase");

        jButtonNovaFase.setText("Novo");
        jButtonNovaFase.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonNovaFaseMouseClicked(evt);
            }
        });

        jLabelCliente.setText("Cliente");

        jLabelStatus.setText("Status");

        jComboBoxStatus1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Ativo", "Inativo" }));

        jComboBoxStatus2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Autor", "Litisconsorte", "Réu" }));

        jLabelParteOposta.setText("Parte Oposta");

        jLabelAdvogadoOposto.setText("Advogado Oposto");

        jLabelJuiz.setText("Juiz");

        jButtonNovoJuiz.setText("Novo");
        jButtonNovoJuiz.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonNovoJuizMouseClicked(evt);
            }
        });

        jLabelValorDaCausa.setText("Valor da Causa");

        jLabelHonorarios.setText("Honorários");

        jLabelObservacoes.setText("Observações");

        jTextAreaObservacoes.setColumns(20);
        jTextAreaObservacoes.setRows(5);
        jScrollPane1.setViewportView(jTextAreaObservacoes);

        jLabelEstrategia.setText("Estratégia");

        jTextAreaEstrategia.setColumns(20);
        jTextAreaEstrategia.setRows(5);
        jScrollPane2.setViewportView(jTextAreaEstrategia);

        jButtonSalvar.setText("Salvar");
        jButtonSalvar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonSalvarMouseClicked(evt);
            }
        });

        jButtonLimpar.setText("Limpar");
        jButtonLimpar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonLimparMouseClicked(evt);
            }
        });

        jButtonFechar.setText("Fechar");
        jButtonFechar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonFecharMouseClicked(evt);
            }
        });

        jButtonNovaComarca.setText("Novo");
        jButtonNovaComarca.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonNovaComarcaMouseClicked(evt);
            }
        });

        jButtonNovaVara.setText("Novo");
        jButtonNovaVara.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonNovaVaraMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelProcesso)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldProcesso, javax.swing.GroupLayout.DEFAULT_SIZE, 437, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelComarca)
                                    .addComponent(jLabelVara)
                                    .addComponent(jLabelTipoDaAcao)
                                    .addComponent(jLabelFase)
                                    .addComponent(jLabelCliente)
                                    .addComponent(jLabelStatus))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jComboBoxStatus1, 0, 187, Short.MAX_VALUE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jComboBoxStatus2, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jComboBoxCliente, 0, 366, Short.MAX_VALUE)
                                    .addComponent(jComboBoxFase, 0, 366, Short.MAX_VALUE)
                                    .addComponent(jComboBoxTipoDaAcao, 0, 366, Short.MAX_VALUE)
                                    .addComponent(jComboBoxVara, 0, 366, Short.MAX_VALUE)
                                    .addComponent(jComboBoxComarca, 0, 366, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButtonNovaVara)
                                    .addComponent(jButtonNovaComarca)
                                    .addComponent(jButtonNovaFase)
                                    .addComponent(jButtonNovoTipoDaAcao)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelParteOposta)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldParteOposta, javax.swing.GroupLayout.DEFAULT_SIZE, 411, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelAdvogadoOposto)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldAdvogadoOposto, javax.swing.GroupLayout.DEFAULT_SIZE, 381, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelJuiz)
                                    .addComponent(jLabelValorDaCausa))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jComboBoxJuiz, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButtonNovoJuiz))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jTextFieldValorDaCausa, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabelHonorarios)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextFieldHonorarios, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelObservacoes)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 412, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelEstrategia)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 430, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(123, 123, 123)
                        .addComponent(jButtonSalvar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonLimpar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonFechar)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelProcesso)
                    .addComponent(jTextFieldProcesso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelComarca)
                    .addComponent(jComboBoxComarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonNovaComarca))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelVara)
                    .addComponent(jComboBoxVara, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonNovaVara))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTipoDaAcao)
                    .addComponent(jComboBoxTipoDaAcao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonNovoTipoDaAcao))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelFase)
                    .addComponent(jComboBoxFase, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonNovaFase))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCliente)
                    .addComponent(jComboBoxCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelStatus)
                    .addComponent(jComboBoxStatus1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxStatus2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelParteOposta)
                    .addComponent(jTextFieldParteOposta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelAdvogadoOposto)
                    .addComponent(jTextFieldAdvogadoOposto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelJuiz)
                            .addComponent(jComboBoxJuiz, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelValorDaCausa)
                            .addComponent(jTextFieldValorDaCausa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelHonorarios)
                            .addComponent(jTextFieldHonorarios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jButtonNovoJuiz))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelObservacoes)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelEstrategia)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonSalvar)
                    .addComponent(jButtonLimpar)
                    .addComponent(jButtonFechar))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonFecharMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonFecharMouseClicked
        habilitaBotoesBarraDeFerramentas();
        areaDeTrabalho.removeAll();
        areaDeTrabalho.revalidate();
        areaDeTrabalho.repaint();
    }//GEN-LAST:event_jButtonFecharMouseClicked

    private void jButtonLimparMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonLimparMouseClicked
        limpaCampos();
    }//GEN-LAST:event_jButtonLimparMouseClicked

    private void jButtonNovaVaraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonNovaVaraMouseClicked
        VaraGUI vg = new VaraGUI(advogadoFacade,null, true);
        vg.setVisible(true);
        carregaVara();
    }//GEN-LAST:event_jButtonNovaVaraMouseClicked

    private void jButtonNovaComarcaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonNovaComarcaMouseClicked
        ComarcaGUI cg = new ComarcaGUI(advogadoFacade,null, true);
        cg.setVisible(true);
        carregaComarca();
    }//GEN-LAST:event_jButtonNovaComarcaMouseClicked

    private void jButtonNovoJuizMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonNovoJuizMouseClicked
        JuizGUI jg = new JuizGUI(advogadoFacade, null, true);
        jg.setVisible(true);
        carregaJuiz();
    }//GEN-LAST:event_jButtonNovoJuizMouseClicked

    private void jButtonNovaFaseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonNovaFaseMouseClicked
        FaseGUI fg = new FaseGUI(advogadoFacade, null, true);
        fg.setVisible(true);
        carregaFase();
    }//GEN-LAST:event_jButtonNovaFaseMouseClicked

    private void jButtonNovoTipoDaAcaoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonNovoTipoDaAcaoMouseClicked
        AcaoGUI ag = new AcaoGUI(advogadoFacade, null, true);
        ag.setVisible(true);
        carregaAcao();
    }//GEN-LAST:event_jButtonNovoTipoDaAcaoMouseClicked

    private void jButtonSalvarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonSalvarMouseClicked
        // TODO add your handling code here:
        String nome = jTextFieldProcesso.getText();
        Comarca comarca = (Comarca) jComboBoxComarca.getSelectedItem();
        Vara vara = (Vara) jComboBoxVara.getSelectedItem();
        Acao acao = (Acao) jComboBoxTipoDaAcao.getSelectedItem();
        Fase fase = (Fase) jComboBoxFase.getSelectedItem();
        Cliente cliente = (Cliente) jComboBoxCliente.getSelectedItem();
        String status = jComboBoxStatus1.getSelectedItem().toString();
        String posicao = jComboBoxStatus2.getSelectedItem().toString();
        String parteOposta = jTextFieldParteOposta.getText();
        String advogadoOposto = jTextFieldAdvogadoOposto.getText();
        Juiz juiz = (Juiz) jComboBoxJuiz.getSelectedItem();
        Double valorDaCausa = Double.parseDouble(jTextFieldValorDaCausa.getText());
        Double honorarios = Double.parseDouble(jTextFieldHonorarios.getText());
        String observacoes = jTextAreaObservacoes.getText();
        String estrategia = jTextAreaEstrategia.getText();

        //try {
            advogadoFacade.CriarProcesso(nome, comarca.getId(), vara.getId(), acao.getId(), fase.getId(), cliente.getId(), juiz.getId(), status, posicao, parteOposta, advogadoOposto, valorDaCausa, honorarios, observacoes, estrategia);
            JOptionPane.showMessageDialog(null, "Processo "+nome+" salvo com sucesso.");
            limpaCampos();
        //} catch (AtributoNaoEncontrado ex) {
          //  System.out.println("Falta algum atributo.");
            //Logger.getLogger(ClienteGUI.class.getName()).log(Level.SEVERE, null, ex);
          //JOptionPane.showMessageDialog(null, ex.getMessage() ,"Erro",JOptionPane.ERROR_MESSAGE);
            //jTextField_Nome.grabFocus();
            //jFormattedTextField_CEP.grabFocus();
        //}

    }//GEN-LAST:event_jButtonSalvarMouseClicked

    private void habilitaBotoesBarraDeFerramentas(){
        for (Component botoes: barraDeFerramentas.getComponents()) {
            botoes.setEnabled(true);
        }
        System.out.println("");
        System.out.println("Todos os botoes habilitados.");
    }

    private void limpaCampos(){
        
    }

    private void carregaVara () {
        jComboBoxVara.removeAllItems();
        System.out.println("");
        System.out.println("Carregando varas");
        for (Vara vara : advogadoFacade.getTodasVaras()) {
            jComboBoxVara.addItem(vara);
            System.out.println("Vara: "+ vara.getId() + " - " + vara.getNome());
        }
        System.out.println("Tamanho da lista de varas:" + jComboBoxVara.getItemCount());
        System.out.println("Varas carregadas");
    }

    private void carregaComarca () {
        jComboBoxComarca.removeAllItems();
        System.out.println("");
        System.out.println("Carregando comarcas");
        for (Comarca comarca : advogadoFacade.getTodasComarcas()) {
            jComboBoxComarca.addItem(comarca);
            System.out.println("Comarca: "+ comarca.getId() + " - " + comarca.getNome());
        }
        System.out.println("Tamanho da lista de comarcas: " + jComboBoxComarca.getItemCount());
        System.out.println("Comarcas carregadas.");
    }

    private void carregaCliente () {
        jComboBoxCliente.removeAllItems();
        System.out.println("");
        System.out.println("Carregando clientes");
        for (Cliente cliente : advogadoFacade.getTodosClientes()) {
            jComboBoxCliente.addItem(cliente);
            System.out.println("Cliente: "+ cliente.getId() + " - " + cliente.getNome());
        }
        System.out.println("Tamanho da lista de clientes: " + jComboBoxComarca.getItemCount());
        System.out.println("Clientes carregados.");
    }

    private void carregaJuiz () {
        jComboBoxJuiz.removeAllItems();
        System.out.println("");
        System.out.println("Carregando juizes");
        for (Juiz juiz : advogadoFacade.getTodosJuizes()) {
            jComboBoxJuiz.addItem(juiz);
            System.out.println("Juiz: "+ juiz.getId() + " - " + juiz.getNome());
        }
        System.out.println("Tamanho da lista de juizes: " + jComboBoxJuiz.getItemCount());
        System.out.println("Juizes carregados.");
    }

    private void carregaFase() {
        jComboBoxFase.removeAllItems();
        System.out.println("");
        System.out.println("Carregando fases");
        for (Fase fase : advogadoFacade.getTodasFases()) {
            jComboBoxFase.addItem(fase);
            System.out.println("Fase: "+ fase.getId() + " - " + fase.getNome());
        }
        System.out.println("Tamanho da lista de fases: " + jComboBoxFase.getItemCount());
        System.out.println("fases carregados.");
    }

    private void carregaAcao() {
        jComboBoxTipoDaAcao.removeAllItems();
        System.out.println("");
        System.out.println("Carregando tipo de ações");
        for (Acao acao : advogadoFacade.getTodasAcoes()) {
            jComboBoxTipoDaAcao.addItem(acao);
            System.out.println("Tipo de Ação: "+ acao.getId() + " - " + acao.getNome());
        }
        System.out.println("Tamanho da lista de tipo de ações: " + jComboBoxTipoDaAcao.getItemCount());
        System.out.println("Tipo de ações carregados.");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonFechar;
    private javax.swing.JButton jButtonLimpar;
    private javax.swing.JButton jButtonNovaComarca;
    private javax.swing.JButton jButtonNovaFase;
    private javax.swing.JButton jButtonNovaVara;
    private javax.swing.JButton jButtonNovoJuiz;
    private javax.swing.JButton jButtonNovoTipoDaAcao;
    private javax.swing.JButton jButtonSalvar;
    private javax.swing.JComboBox jComboBoxCliente;
    private javax.swing.JComboBox jComboBoxComarca;
    private javax.swing.JComboBox jComboBoxFase;
    private javax.swing.JComboBox jComboBoxJuiz;
    private javax.swing.JComboBox jComboBoxStatus1;
    private javax.swing.JComboBox jComboBoxStatus2;
    private javax.swing.JComboBox jComboBoxTipoDaAcao;
    private javax.swing.JComboBox jComboBoxVara;
    private javax.swing.JLabel jLabelAdvogadoOposto;
    private javax.swing.JLabel jLabelCliente;
    private javax.swing.JLabel jLabelComarca;
    private javax.swing.JLabel jLabelEstrategia;
    private javax.swing.JLabel jLabelFase;
    private javax.swing.JLabel jLabelHonorarios;
    private javax.swing.JLabel jLabelJuiz;
    private javax.swing.JLabel jLabelObservacoes;
    private javax.swing.JLabel jLabelParteOposta;
    private javax.swing.JLabel jLabelProcesso;
    private javax.swing.JLabel jLabelStatus;
    private javax.swing.JLabel jLabelTipoDaAcao;
    private javax.swing.JLabel jLabelValorDaCausa;
    private javax.swing.JLabel jLabelVara;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextAreaEstrategia;
    private javax.swing.JTextArea jTextAreaObservacoes;
    private javax.swing.JTextField jTextFieldAdvogadoOposto;
    private javax.swing.JTextField jTextFieldHonorarios;
    private javax.swing.JTextField jTextFieldParteOposta;
    private javax.swing.JTextField jTextFieldProcesso;
    private javax.swing.JTextField jTextFieldValorDaCausa;
    // End of variables declaration//GEN-END:variables

}