/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ClienteRelatorioGUI.java
 *
 * Created on 06/03/2010, 11:44:13
 */
package gui;

import facade.AdvogadoFacade;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.Cliente;

/**
 *
 * @author andrehadm
 */
public class ClienteRelatorioGUI extends javax.swing.JPanel {

    AdvogadoFacade advogadoFacade;

    /** Creates new form ClienteRelatorioGUI */
    public ClienteRelatorioGUI(AdvogadoFacade advogadoFacade) {
        this.advogadoFacade = advogadoFacade;
        initComponents();
        carregaClientes();
    }

    public void carregaClientes() {
        System.out.println("");
        System.out.println("Carregando clientes");
        List <Cliente> cliente = advogadoFacade.getTodosClientes();
        
        Object[][] clienteTable = new Object[cliente.size()][4]; // Define uma matriz bidimensional para armazenar os valores
        Object[] titulo = new Object[4]; // Define uma matriz unidimensional para armazenar os titulos


        jTable1.removeAll();
        int clienteContador = 0;
        for (Cliente clienteFor : advogadoFacade.getTodosClientes()) {
            clienteTable[clienteContador][0] = clienteFor.getId().toString();
            clienteTable[clienteContador][1] = clienteFor.getNome();
            clienteTable[clienteContador][2] = clienteFor.getTelefone();
            clienteTable[clienteContador][3] = clienteFor.getCelular();
            clienteContador++;
            System.out.println("Cliente: "+ clienteFor.getId() + " - " + clienteFor.getNome());
        }
        //System.out.println("Tamanho da lista de clientes: " + jComboBoxCliente.getItemCount());
        System.out.println("Clientes carregados.");

        // titulos
        titulo[0] = "Id";
        titulo[1] = "Nome";
        titulo[2] = "Telefone";
        titulo[3] = "Celular"; // criando objeto modelo

        DefaultTableModel modelo = new DefaultTableModel(clienteTable, titulo);

        // definindo o modelo da tabela
        jTable1.setModel(modelo);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Cliente", "Telefone", "Celular"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        
        int coluna= jTable1.getSelectedColumn();
        int linha = jTable1.getSelectedRow();
        String valor = (String) jTable1.getValueAt(linha, coluna);
        JOptionPane.showMessageDialog(null, "coluna "+coluna+" linha "+linha+ " Valor= "+valor);
    }//GEN-LAST:event_jTable1MouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
